// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQbP6s1igiCpv0wVy5qgek1BRNwpPygk',
    appId: '1:983679982151:web:02fa25996b3a8603bc2f62',
    messagingSenderId: '983679982151',
    projectId: 'messengerdb-1d596',
    authDomain: 'messengerdb-1d596.firebaseapp.com',
    storageBucket: 'messengerdb-1d596.appspot.com',
    measurementId: 'G-X9JCWCF9Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn6rtafZEYGTxUPN-sD8zCKk_bfDbe4Q8',
    appId: '1:983679982151:android:4cc9ed5d38ad3774bc2f62',
    messagingSenderId: '983679982151',
    projectId: 'messengerdb-1d596',
    storageBucket: 'messengerdb-1d596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD39uylQpd5kvvfiyC8y4319DRa8pi-nuQ',
    appId: '1:983679982151:ios:3dc38659ceba030bbc2f62',
    messagingSenderId: '983679982151',
    projectId: 'messengerdb-1d596',
    storageBucket: 'messengerdb-1d596.appspot.com',
    iosBundleId: 'com.example.messengerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD39uylQpd5kvvfiyC8y4319DRa8pi-nuQ',
    appId: '1:983679982151:ios:ae4926be9c2771d2bc2f62',
    messagingSenderId: '983679982151',
    projectId: 'messengerdb-1d596',
    storageBucket: 'messengerdb-1d596.appspot.com',
    iosBundleId: 'com.example.messengerapp.RunnerTests',
  );
}
